import Header from '../components/header/header';
import './styles/globals.scss';
import { Roboto } from 'next/font/google';
import clsx from 'clsx';
//npm i clsx

//preload : true 사용시, 루트레이아웃에 적용시 전역걸쳐 프리로드
/*
  외부폰트 적용시 display 옵션별 기능 설명
  참조링크: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display
  auto: 사용하는 브라우저의 user agent설정값에 따라서 자동으로 외부폰트 적용설정을 사용
  block: 적은 대기시간 설정후 외부폰트 적용될때까지 계속해도 시도
  swap: block보다 대기시간을 더 짧게 설정하고 외부폰트 적용될때까지 계속 시도
  fallback: 대기시간도 짧게 폰트적용도 시도도 짧게 처리해서 외부폰트 미적용시 바로 대체 시스템폰트 적용
  optional: 대기시간을 짧게 설정하고 외부폰트 시도를 무시

  block period: 외부폰트가 import되기 아무것도 보이지 대채폰트가 적용된 상태
  font swap period: 외부폰트를 적용하려고 시도하는 상태
  failure period: 외부폰트 연결을 실패로 인지하는 상태

*/

const roboto = Roboto({
	weight: '400',
	subsets: ['latin'],
	display: 'swap',
	preload: true, //subsets가 지정되있을 시 프리로드 사용
	variable: '--font-roboto',
});

const isRoboto = false;

export const metadata = {
	title: 'Main',
	description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			{/* clsx활용시 변수에 조건문 적용 가능 */}
			<body className={clsx('wrap', isRoboto && roboto.variable)}>
				<Header />
				<h1>No google Font</h1>
				<h1>Google font</h1>
				{children}
			</body>
		</html>
	);
}

/*
  Next에서의 기능별 컴포넌트 구분
  Page Component 
  --페이지로 출력될 틀 컴포넌트 
  --about/page.jsx, gallery/page.jsx
  --따로 설정을 하지 않으면 기본적으로 Server에서 동작되서 prepage로 사전 렌더링

  Partial Component 
  --페이지 안쪽에서 호출되면서 부분적인 UI나 기능을 담당하는 컴포넌트 
  --componets>header.jsx, componets/popup.jsx 같은 것들
*/
